server:
  port: 8003
spring:
  application:
    name: peng-consumer-dept-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://peng:123456@localhost:9001/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true