server:
  port: 9003
eureka:
  instance:
    hostname: peng-eureka-9003
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://user:password@localhost:9001/eureka,http://user:password@localhost:9002/eureka
security:
  basic:
    enabled: true
  user:
    name: peng
    password: 123456




